<h1>Python: without numpy or sklearn </h1>

                                                                                             Created By: Rahul Dable
                                                                                          

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

#### Solution:

In [1]:
# reference: https://www.geeksforgeeks.org/multiplication-two-matrices-single-line-using-numpy-python/

def matrix_mul(A:'First Matric', 
               B:'Second Matric') -> 'Returns Multiplication':
    
    if len(A[0]) == len(B):
        result = [[0 for x in range(len(B[0]))] for y in range(len(A))]
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    result[i][j] += int(A[i][k] * B[k][j])
        print(result)
    else:
        print("Matrix Multiplication is NOT Possible")

In [2]:
A  = [[1, 3, 4],
     [2, 5, 7]]

B   = [ [1, 2],
        [4, 5],
        [7, 8]]

matrix_mul(A, B)

[[41, 49], [71, 85]]


In [3]:
A = [[1, 2],
    [3, 4]]

B = [[1, 2, 3, 4, 5],
    [5, 6, 7, 8, 9]]
        
matrix_mul(A, B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


In [4]:
A   = [[1, 3, 4],
        [2, 5, 7],
        [5, 9, 6]]
    
B   = [[1, 0, 0,],
        [0, 1, 0,],
        [0, 0, 1,]]

matrix_mul(A, B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


In [5]:
A = [[1, 2],
     [3, 4]]

B = [[1, 4],
     [5, 6],
     [7, 8],
     [9, 6]]

matrix_mul(A, B)

Matrix Multiplication is NOT Possible


_________

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

#### Solution:

In [6]:
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79, 150]

In [7]:
import random
from collections import Counter, OrderedDict

def pick_a_number_from_list(A:"List of random numbers") -> 'Returns random numbers with prob. propertional to its magntude':
    
    #Caclulating Normalised Cummalitive Sum
    A_sum = sum(A)
    A_sum_norm = [ele/A_sum for ele in A]
    A_norm_cumsum = []
    cumsum = 0
    for ele in A_sum_norm:
        cumsum += ele
        A_norm_cumsum.append(cumsum)
    
    #selecting random number
    #selected_number = 0
    rand_num_index = random.uniform(0.0, 1.0)
    for ele in range(len(A_norm_cumsum)):
        if rand_num_index < A_norm_cumsum[ele]:
            selected_number = A[ele]
            break
    return selected_number

number_of_sampled = 100

sampled_numbers = []
def sampling_based_on_magnitude():
    for i in range(number_of_sampled):
        sampled_numbers.append(pick_a_number_from_list(A))
    return print(sampled_numbers)
    
sampling_based_on_magnitude()

print('='*50)

output = dict(Counter(sampled_numbers))
output = OrderedDict(sorted(output.items(), reverse=True))
for key, values in output.items():
    print("number {0} : frequency {1} ".format(key, values))

[79, 150, 45, 150, 45, 79, 79, 79, 79, 27, 150, 28, 45, 79, 79, 28, 13, 79, 28, 10, 28, 150, 100, 150, 45, 5, 79, 10, 150, 150, 150, 79, 45, 79, 150, 28, 10, 150, 150, 150, 150, 45, 100, 79, 27, 150, 150, 45, 100, 150, 27, 150, 45, 150, 13, 150, 79, 100, 45, 10, 6, 150, 28, 150, 79, 150, 150, 79, 150, 100, 27, 79, 79, 150, 150, 150, 100, 79, 79, 79, 10, 100, 45, 28, 150, 45, 28, 150, 27, 150, 150, 100, 79, 79, 150, 45, 28, 150, 150, 28]
number 150 : frequency 34 
number 100 : frequency 8 
number 79 : frequency 22 
number 45 : frequency 12 
number 28 : frequency 10 
number 27 : frequency 5 
number 13 : frequency 2 
number 10 : frequency 5 
number 6 : frequency 1 
number 5 : frequency 1 


___________

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

#### Solution:

In [8]:
import re

pattern1 = r'\D'
pattern2 = r'\d'

def replace_digits(myString:'Input String'):
    myString = re.sub(pattern1, '', myString)
    myString = re.sub(pattern2, '#', myString)
    return myString


In [9]:
list_of_Strings = ['234', 'a2b3c4', 'abc', '#2a$#b%c%561#']
output = list(map(replace_digits, list_of_Strings ))
output

['###', '###', '', '####']

In [10]:
list_of_Strings = ['234', 'a2b3c4', 'abc', '#2a$#b%c%561#']
output = list(map(replace_digits, list_of_Strings ))
output = dict(zip(list_of_Strings, output))
for key, values in output.items():
    print("{0} => {1} ".format(key, values))

234 => ### 
a2b3c4 => ### 
abc =>  
#2a$#b%c%561# => #### 


________

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

#### Solution:

In [11]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

In [31]:
def compute_percentile(Marks:'List of Marks obtained by students', 
                       percentile:'Percentile value to compute') -> 'Returns percentile value':
    
    m = int(round(percentile * len(Marks)))
    return Marks[m-1]

def display_dash_board(Students:'List of Students', 
                       Marks:'List of Marks') -> 'Display Dashboard':
    
    marklists = dict(zip(Marks, Students))
    
    #Computing Top 5 Students
    Marks_descending = sorted(Marks, reverse=True)
    top_5_students = [marklists[x] for x in Marks_descending[0:5]]
    
    #Computing least 5 Students
    Marks_ascending = sorted(Marks, reverse=False)
    least_5_students = [marklists[x] for x in Marks_ascending[0:5]]
    
    #students_within_25_and_75 = # compute this
    
    Marks_within_25_and_75 = []
    for marks in Marks_ascending:
        if marks > compute_percentile(Marks_ascending, 0.25) and marks < compute_percentile(Marks_ascending, 0.75):
            Marks_within_25_and_75.append(marks)
    students_within_25_and_75 = [marklists[x] for x in Marks_within_25_and_75]

    
   #return  print("Top 5 Students",top_5_students) , print("least 5 Students",least_5_students), print(students_within_25_and_75)
    return  top_5_students , least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)


In [32]:
print("Name of Top 5 Students are   :" ,top_5_students)
print("Name of least 5 Students are :" ,least_5_students)
print("Name of Students within 25 - 75 percentile range are :" ,students_within_25_and_75)

Name of Top 5 Students are   : ['student8', 'student10', 'student2', 'student5', 'student7']
Name of least 5 Students are : ['student3', 'student4', 'student9', 'student6', 'student1']
Name of Students within 25 - 75 percentile range are : ['student9', 'student6', 'student1', 'student7', 'student5']


__________

<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

#### Solution:

In [14]:
S = [(1,2), (3,4), (-1,1), (6,-7), (0, 6), (-5,-8), (-1,-1), (6,0), (1,-1)]
P = [(3,-4)]

In [15]:
import math

def compute_cosine_dist(first_point:'List of surrounding points', 
                        another_point: 'Point from where need to calculate distance')-> 'Returns Cosine Distance':

    #Calculate Cosine Distance
    num = first_point[0]*another_point[0] + first_point[1]*another_point[1] 
    denom = math.sqrt((math.pow(first_point[0], 2) + (math.pow(first_point[1], 2)))) * \
            math.sqrt((math.pow(another_point[0], 2) + (math.pow(another_point[1], 2))))

    cosine_dist = math.acos(num/denom)
    return cosine_dist

another_point = list(P[0])
cosine_distances = []
for first_point in S:
    #print(first_point)
    cosine_dist = compute_cosine_dist(first_point, another_point)
    #print(cosine_dist)
    cosine_distances.append(cosine_dist)
#print(cosine_distances)

#creating dict to lookup points according to their distance
cosine_distances_dict = dict(zip(cosine_distances, S))
#cosine_distances_dict = dict(OrderedDict(sorted(cosine_distances_dict.items(), reverse = False)))
#print(cosine_distances_dict)

#Selecting 5 closest points
cosine_distances = sorted(cosine_distances, reverse= False)
closest_5_distance = cosine_distances[0:5]
#print(closest_5_points)

#selecting closest 5 points
closest_5_points = [cosine_distances_dict[pts] for pts in closest_5_distance]
print("Five Closest Points are : ", closest_5_points)

Five Closest Points are :  [(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


_________

<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

#### Solution:

In [16]:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

In [17]:
import math
import re

def compute_dist(line:'Select One Line', 
                 pt:'Select any point') -> 'Returns Distance of point from given line':
    distance = (line[0]*pt[0] + line[1]*pt[1] + line[2]) / math.sqrt(math.pow(line[0],2) + math.pow(line[1],2))
    return distance   
    

def point_classifier(Red:"List of points belongs to first category", 
                     Blue:"List of points belongs to another category", 
                     Lines:"List of given lines") -> "Returns if the line classify the points correctly":
    
    #String Parsing
    results = []
    lines_coeff = []
    pattern = r'[^a-zA-Z]+'
    for line in Lines:
        line_coordinates = [float(d) for d in re.findall(pattern, line)]
        #print(line, line_coordinates)
        lines_coeff.append(line_coordinates)

    #print("Lines Coordinates Are : ", lines_coeff)
    #print("="*80)

    for i in range(len(Lines)):
        red_distances = []
        blue_distances = []
        line = lines_coeff[i]
        #print("line :", i+1)
        #print("Distance of points from the line ", Lines[i])

        for red_pt in Red:
            pt = list(red_pt)
            red_dist = compute_dist(line, pt)
            red_distances.append(red_dist)
        #print("Red Points Dist", red_distances)

        for blue_pt in Blue:
            pt = list(blue_pt)
            blue_dist = compute_dist(line, pt)
            blue_distances.append(blue_dist)
        #print("Blue Points Dist", blue_distances)
    
        #Checking if all points from same category lies on same side of the line
        red_test = []
        for ele in red_distances:
            if  ele > 0:
                #result = 1
                red_test.append(1)
            else:
                red_test.append(-1)
            #print(red_test)

        blue_test = []
        for ele in blue_distances:
            if  ele > 0:
                #result = 1
                blue_test.append(1)
            else:
                blue_test.append(-1)
            #print(blue_test)

        if len(set(red_test)) == 1 and len(set(blue_test)) == 1: 
            if red_test[0] != blue_test[0]:
                result = 'Yes'
                results.append(result)
            else:
                result = 'No'
                results.append(result)
        else:
            result = 'No'
            results.append(result)
        #print("="*80)
    return results
    
    

In [18]:
output = point_classifier(Red, Blue, Lines)
print("Output :")
print(dict(zip(Lines, output)))

Output :
{'1x+1y+0': 'Yes', '1x-1y+0': 'No', '1x+0y-3': 'No', '0x+1y-0.5': 'Yes'}


_________

<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



#### Solution:

In [19]:
import re

def curve_smoothing(input_str:'Input String') -> 'Return filled values':
    
    #String Parsing
    pattern = r"\,"
    input_str = re.sub(pattern, ' ', input_str)
    input_str = input_str.split()
    
    #replacing missing values with 0 and converting string into integer
    for i in range(len(input_str)):
        try:
            input_str[i] = int(input_str[i])
        except:
            input_str[i] = 0

    #We have two types of pattern, applying specific rules as per pattern
    
    if input_str[0] or input_str[-1] != 0:
        sum_ = sum(input_str)
        output = [int(sum_/len(input_str)) for ele in input_str]
    
    else:
        output = []
        for i in range(len(input_str)):
            if input_str[i] == 0:
                output.append(input_str[i])
            else:
                update = int(input_str[i]/(i+1))
                output.append(update)
                break
        output = [int(update) if ele == 0 else ele for ele in output]

        for j in range(i+1, len(input_str), 1):
            if input_str[j] == 0:
                output.append(input_str[j])
            else:
                update2 = (update + input_str[j])/(j-1)
                output.append(int(update2))
                break
        output = [int(update2) if ele == 0 else ele for ele in output]

        count = 0
        for k in range(j+1,len(input_str),1):   
            if input_str[k]==0:
                output[j] = 0
                input_str[k-1] == 0
                output.append(input_str[k])
                count +=1

        update3 = int(update2/(count+1))
        output = [int(update3) if ele == 0 else ele for ele in output]

    return output
    

In [20]:
given_strings = ["_,_,_,24", "40,_,_,_,60", "80,_,_,_,_", "_,_,30,_,_,_,50,_,_"]

In [21]:
output_ = map(curve_smoothing, given_strings)
for i in output_:
    print(i)

[6, 6, 6, 6]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[10, 10, 10, 12, 12, 12, 4, 4, 4]


_________

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




#### Solution:

In [22]:
data = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

In [23]:
import itertools
def compute_conditional_probabilites(data:'Input list of list') -> 'Returns conditional prob of all possible combinations':
    #calculating unique first and second element
    first_element = []
    second_element = []
    for ele in data:
        first_element.append(ele[0])
        second_element.append(ele[1])
    
    #listing and sorting first unique elements
    first_element = list(set(first_element))
    first_element.sort(reverse=False)
    
    #listing and sorting second unique elements
    second_element = list(set(second_element))
    second_element.sort(reverse=False)

    #calculating occurance of second element
    denoms= []
    for i in range(len(second_element)):
        denom = 0
        for j in range(len(data)):
            if data[j][1] == second_element[i]:
                denom += 1
        denoms.append(denom)
    
    second_ele_freq = dict(zip(second_element, denoms))

    #calculating frequency of ocurance of all possible combinations
    all_possible_combinations = list(itertools.product(first_element, second_element))
    combination_freq = []
    for ele in all_possible_combinations:
        counter_ = 0
        for data_ele in data:
            if list(data_ele) == list(ele):
                counter_ += 1 
        combination_freq.append(counter_)

    combination_freq_dict = dict(zip(all_possible_combinations, combination_freq))
    
    #Calculating conditional probability
    cond_prob = []
    for ele_ in all_possible_combinations:
        prob = round(combination_freq_dict.get(ele_)/second_ele_freq[list(ele_)[1]], 2)
        cond_prob.append(prob)
        a = second_ele_freq[list(ele_)[1]]
        b = combination_freq_dict.get(ele_)
        #print('{}/{} '.format(b,a))
        #print("F={0}|S={1}  ".format(ele_[0], ele_[1]))
        print("probability of (F={0}|S={1}) = {2}/{3}  ({4}) ".format(ele_[0], ele_[1], b, a, prob))
    #return all_possible_combinations, a, b, prob
    

In [24]:
compute_conditional_probabilites(data)

probability of (F=F1|S=S1) = 1/4  (0.25) 
probability of (F=F1|S=S2) = 1/3  (0.33) 
probability of (F=F1|S=S3) = 0/3  (0.0) 
probability of (F=F2|S=S1) = 1/4  (0.25) 
probability of (F=F2|S=S2) = 1/3  (0.33) 
probability of (F=F2|S=S3) = 1/3  (0.33) 
probability of (F=F3|S=S1) = 0/4  (0.0) 
probability of (F=F3|S=S2) = 1/3  (0.33) 
probability of (F=F3|S=S3) = 1/3  (0.33) 
probability of (F=F4|S=S1) = 1/4  (0.25) 
probability of (F=F4|S=S2) = 0/3  (0.0) 
probability of (F=F4|S=S3) = 1/3  (0.33) 
probability of (F=F5|S=S1) = 1/4  (0.25) 
probability of (F=F5|S=S2) = 0/3  (0.0) 
probability of (F=F5|S=S3) = 0/3  (0.0) 


___________

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

#### Solution:

In [25]:
def string_features(S1:'First input string', 
                    S2:'Second input string') -> 'Returns Desirable words and count':
    
    #Creating set of all unique words
    S1_words = set(S1.split())
    S2_words = set(S2.split())
    word_dict = S1_words.union(S2_words)
    
    #All unique words in S1 and S2
    unique_words = list(S1_words.union(S2_words))
    
    #Number of common words between S1, S2
    common_words = len(list(S1_words.intersection(S2_words)))
    
    #Words in S1 but not in S2
    
    words_in_S1 = list(word_dict.symmetric_difference(S2_words))
    
    #Words in S2 but not in S1
    words_in_S2 = list(word_dict.symmetric_difference(S1_words))

    return common_words, words_in_S1, words_in_S2


In [26]:
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

common_words, words_in_S1, words_in_S2 = string_features(S1, S2)

print("Number of common words between S1, S2 :", common_words)
print("Words in S1 but not in S2             :", words_in_S1)
print("Words in S2 but not in S1             :", words_in_S2)

Number of common words between S1, S2 : 7
Words in S1 but not in S2             : ['5', 'first', 'F']
Words in S2 but not in S1             : ['3', 'S', 'second']


__________

<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

#### Solution:

In [48]:
def compute_log_loss(X):
    sub_sum = 0

    for sublist in X:
        sub_x = sublist[0]*(math.log10(sublist[1])) + (1 - sublist[0])*(math.log10(1-sublist[1]))
        sub_sum += sub_x
        loss = -(sub_sum)/len(X)
    return loss

In [49]:
X = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(X)
print(loss)

0.42430993457031635
